Seven
drfox81/demo2 pull request #7
Opened 2023-01-31 17:48 UTC by drfox81

2023-02-01 09:31 UTC, alekseykoshelev requested changes

2023-02-01 09:31 UTC, alekseykoshelev commented on src/main/java/com/example/demo/services/impl/IngredientServiceImpl.java
> +        return ingredientMap.getOrDefault(id, null);
Тут можно заменить просто на `return ingredientMap.getOrDefault(id, null);`

2023-02-01 09:31 UTC, alekseykoshelev commented on src/main/java/com/example/demo/services/impl/RecipeServiceImpl.java
> +        saveToFile();
Условие на 49 строке ни на что не влияет. Код одинаковый в обоих ветках. Может тогда убрать проверку. Код сильно сократится.

2023-02-01 09:31 UTC, alekseykoshelev commented on src/main/java/com/example/demo/services/impl/RecipeServiceImpl.java
> +        return recipeMap.get(recipeName);
Тут можно вернуть `recipeNew` ведь ты его выше положил по ключу.

2023-02-01 09:31 UTC, alekseykoshelev commented on src/main/java/com/example/demo/services/impl/RecipeServiceImpl.java
> +        saveToFile();
А зачем сохранять файл если мы ничего не удалили?

2023-02-01 18:53 UTC, drfox81 commented on src/main/java/com/example/demo/services/impl/IngredientServiceImpl.java
> +        return ingredientMap.getOrDefault(id, null);
у меня именно так и написано

2023-02-01 18:56 UTC, drfox81 commented on src/main/java/com/example/demo/services/impl/RecipeServiceImpl.java
> +        saveToFile();
спасибо, поправил

2023-02-01 18:57 UTC, drfox81 commented on src/main/java/com/example/demo/services/impl/RecipeServiceImpl.java
> +        return recipeMap.get(recipeName);
ключ - название рецепта ,я перезаписал старый рецепт на новый ,и по старому ключу вернул новый рецепт.

2023-02-01 18:58 UTC, drfox81 commented on src/main/java/com/example/demo/services/impl/RecipeServiceImpl.java
> +        saveToFile();
поправил

2023-02-02 16:55 UTC, alekseykoshelev commented on src/main/java/com/example/demo/services/impl/RecipeServiceImpl.java
> +        return recipeMap.get(recipeName);
Не совсем понял что за старый ключ. Ведь ключ у тебя всегда один `recipeName`. По нему ты кладешь и затем по нему же достаешь.

2023-02-02 20:06 UTC, drfox81 commented on src/main/java/com/example/demo/services/impl/RecipeServiceImpl.java
> +        return recipeMap.get(recipeName);
вместо recipeMap.get(recipeName)   вернуть recipeNew?  не понял я , я по факту по ключу recipeName и возвращаю новый рецепт

2023-02-03 19:48 UTC, alekseykoshelev commented on src/main/java/com/example/demo/services/impl/RecipeServiceImpl.java
> +        return recipeMap.get(recipeName);
да, просто можно вот этой операции get избежать, не делать ее еще раз просто так) Мы ведь знаем уже какой результат получим по этой операции, это будет значение `recipeNew`

2023-02-03 19:48 UTC, alekseykoshelev commented on src/main/java/com/example/demo/services/impl/IngredientServiceImpl.java
> +        return ingredientMap.getOrDefault(id, null);
ой, извини, имел ввиду `return ingredientMap.get(id);`

2023-02-04 19:39 UTC, artem-petrosyan commented on src/main/resources/ingredient.json
> +{"0":{"nameIngredients":"Специ вкусу","quantityIngredients":0,"measureUnit":"г."},"1":{"nameIngredients":"Консервированная фасоль","quantityIngredients":400,"measureUnit":"г."},"2":{"nameIngredients"
Так как это файл с данными, то лучше его не пушить в репозиторий.
Предлагаю его удалить из репозитория, а сам файл поместить в .gitignore, чтобы в дальнейшем git его не коммитил.
В сервисах, где этот файл читается, нужно проверить, существует ли файл.
А там, где файл изменяется, проверять, существует ли файл и если нет, то создавать его.
То есть файл будет создан при первой попытке добавить ингридиент.

2023-02-04 19:39 UTC, artem-petrosyan commented on src/main/resources/recipe.json
> +{"Салат для Камиллы из красной фасоли с творожным сыром, красным луком и сезонным салатом":{"nameRecipe":"Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом","cookingTime":7,
Так как это файл с данными, то лучше его не пушить в репозиторий.
Предлагаю его удалить из репозитория, а сам файл поместить в .gitignore, чтобы в дальнейшем git его не коммитил.
В сервисах, где этот файл читается, нужно проверить, существует ли файл.
А там, где файл изменяется, проверять, существует ли файл и если нет, то создавать его.
То есть файл будет создан при первой попытке добавить рецепт.

2023-02-04 19:39 UTC, artem-petrosyan commented on src/main/java/com/example/demo/controllers/FilesController.java
> +        File dataRecipeFile = fileRecipeService.getDataRecipeFile();
Работа с файлом должна производиться в сервисе.
В контроллерах только формируем ответ :)
Предлагаю перенести логику работы с файлом из контроллера в сервис из всех методов контроллера

2023-02-08 16:05 UTC, artem-petrosyan commented on src/main/java/com/example/demo/services/impl/FileIngrServiceImpl.java
> +            if (!Files.exists(Path.of(dataFileIngredientPath, dataFileIngredientName))) {
Тут отрицание не нужно

2023-02-08 16:05 UTC, artem-petrosyan commented on src/main/java/com/example/demo/services/impl/FileIngrServiceImpl.java
> +                return "Файла нет";
Такую строку не получится распарсить и положить в hashmap
Возможно, лучше вернуть null и потом проверить, что вернулся не null

2023-02-08 16:05 UTC, artem-petrosyan commented on src/main/java/com/example/demo/services/impl/FileRecipeServiceImpl.java
> +            if (!Files.exists(Path.of(dataFileRecipePath, dataFileRecipeName))) {
Тут аналогичная неточность, что и в сервисе ингридиентов

2023-02-08 16:42 UTC, drfox81 commented on src/main/java/com/example/demo/services/impl/FileRecipeServiceImpl.java
> +            if (!Files.exists(Path.of(dataFileRecipePath, dataFileRecipeName))) {
спасибо , поправил

2023-02-08 16:42 UTC, drfox81 commented on src/main/java/com/example/demo/services/impl/FileIngrServiceImpl.java
> +            if (!Files.exists(Path.of(dataFileIngredientPath, dataFileIngredientName))) {
спасибо , поправил

2023-02-08 17:05 UTC, drfox81 commented on src/main/java/com/example/demo/services/impl/FileIngrServiceImpl.java
> +                return "Файла нет";
Почему? все работает. при запуске приложения запускается метод и считывает все из файлов, в том числе из ingredient.json, результат проверял, выдает в swagger-е мне ингеидиенты, получается  работает?
    @PostConstruct
    private void init() {
        readRecipeFromFile();
        ingredientService.readIngrFromFile();
    }

2023-02-09 13:29 UTC, artem-petrosyan commented on src/main/java/com/example/demo/services/impl/FileIngrServiceImpl.java
> +                return "Файла нет";
Тут проблема возникнем именно тогда, когда файла ингредиентов не существует.
Тогда мы пойдём по ветке else и вернём строку "Файла нет".
Затем попытаемся распарсить эту строку. 
Но так эта строка не в формате JSON, то парсер упадёт с ошибкой.
Поэтому и предлагают такой кейс учесть :)

2023-02-14 12:16 UTC, closed without merging